### ISSUE TITLE
Issue with downloading models

### ISSUE THREAD

**Issue by bikekowal** [meta-llama/codellama#28]
Hi all,

I am actually struggling with downloading models. When I paste the link when prompted and after tapping 'enter' to download all models I receive the following:

download.sh: 13: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 18: Bad substitution

Tried twice with different links, after removing the cloned repo from HDD.

**Comment by jldefigueiredo** [comment]
same issue here!

**Comment by mkennedym80** [comment]
I'm having the same issue. Same errors. I tried editing the shell script to just use the download link they gave me and still isn't working.

correction, the redirect link they sent via email that you're supposed to paste into the prompt, i tried just assigning that to a variable and skipping entering the value and it's still problematic.

**Comment by mkennedym80** [comment]
ok this is dumb, as i was using sh download.sh

but use '$ bash download.sh' and it'll download.

**Comment by jldefigueiredo** [comment]
It's true. Worked for me too. Thanks. Regards.

**Comment by Kallamamran** [comment]
I use bash download.sh and it doesn't work for me :(
![image](https://github.com/facebookresearch/codellama/assets/25354644/01070df7-0c37-4cd6-ac37-c5f2ff73f707)

**Comment by jldefigueiredo** [comment]
I didnt tried in windows. I used debian

**Comment by Kallamamran** [comment]
Well... It sure doesn't work downloading on my Windows machine 😥

**Comment by jldefigueiredo** [comment]
Email said that url works only for 24hs or a certain amount of downloads

**Comment by Kallamamran** [comment]
Solution for me: Downloading the models from Huggingface - TheBloke in OobaboogaWebUI instead

**Comment by GaganHonor** [comment]
The error messages download.sh: 13: [[: not found and download.sh: 18: Bad substitution suggest that there might be an issue with the shell interpreter being used to run the download.sh script. The [[: not found error message usually occurs when a script that uses Bash-specific syntax is run with a different shell interpreter, such as Dash1. The Bad substitution error message can also occur when a script that uses Bash-specific syntax is run with a different shell interpreter2. To fix this issue, you can try running the ``download.sh`` script with the Bash interpreter by using the command bash download.sh instead of ``sh download.sh``


For more help :   [ Guide by huggingface 🤗 ](https://huggingface.co/blog/codellama#conversational-instructions)

Cheers for @Kallamamran @mkennedym80 They already found 

![ScalerCreateImpactGIF](https://github.com/facebookresearch/codellama/assets/141204441/d6000faf-7c13-43c2-97ca-03d027316e9c)

**Comment by bikekowal** [comment]
> I'm having the same issue. Same errors. I tried editing the shell script to just use the download link they gave me and still isn't working.
> 
> correction, the redirect link they sent via email that you're supposed to paste into the prompt, i tried just assigning that to a variable and skipping entering the value and it's still problematic.

Works well! Thanks!

**Comment by mike-cipherpunk** [comment]
> Solution for me: Downloading the models from Huggingface - TheBloke in OobaboogaWebUI instead

glad you figured it out
