### ISSUE TITLE
Remembering the previous context

### ISSUE THREAD

**Issue by univanxx** [meta-llama/codellama#62]
Hi everyone! Is it possible to make long dialogue with the Instruct model? In other words, to make the model remember a previous context.

For now, I have an idea to paste the previous prompt and the model's response into the new request. Are there more concise and easier ways?

**Comment by GaganHonor** [comment]
Yes, it is possible to have long dialogues with the Instruct model in Codellama 2023 and make the model remember a previous context. While the approach you mentioned of pasting the previous prompt and the model's response into the new request can work, there are more concise and easier ways to achieve this. Here are a few suggestions:

Conversation History: Instead of manually copying and pasting the previous prompt and model's response, you can maintain a conversation history. In Codellama 2023, you can achieve this by providing a list of messages as your input. Each message in the list consists of a 'role' (e.g., 'system', 'user', 'assistant') and 'content' (the text of the message). By appending the previous prompts and model responses to the conversation history, you can maintain context and have longer dialogues.

Token-based Approach: Another approach is to use a token-based strategy. In this approach, you assign specific tokens to represent different parts of the dialogue, such as user prompts, model responses, and conversation history. By using these tokens, you can easily structure and separate the different elements of the dialogue in a concise manner.

Context Managers: Some libraries or frameworks may provide context managers or helper functions to handle conversations and context automatically. These tools can simplify the process of maintaining and updating the dialogue context.

Remember that when working with long dialogues, you need to be mindful of the model's token limit. If the dialogue becomes too long, you may need to truncate or omit parts of the conversation to fit within the model's maximum token limit.

Overall, maintaining a conversation history, using a token-based approach, or leveraging context managers can help you handle long dialogues more efficiently in Codellama 2023. Experiment with these techniques and choose the one that best suits your needs and coding style.

**Comment by univanxx** [comment]
Thank you ChatGPT but I asked for quality advice from a real person ;)

Anyways, I found another way to make a dialogue: update an [instructions](https://github.com/facebookresearch/codellama/blob/cb51c14ec761370ba2e2bc351374a79265d0465e/example_instructions.py#L27) array like that:
```
instructions = [
        [
            {"role": "user", "content": "Message #1"},
            {
                "role": "assistant",
                "content": "Answer #1",
            },
            {"role": "user", "Message #2"},
           ...
        ]
    ]
```

Depending on your maximum context length, model can successfully chat for some time.

**Comment by sidaw** [comment]
The self-answer by @univanxx above is right. If you look at the code, this structured prompt gets concatenated before being fed into the model.

The model support this particular format because it was fine-tuned on such data. To better understand what kind of format and function the model supports, check out how llama is tuned for this (section 3.3): https://arxiv.org/pdf/2307.09288.pdf
