### ISSUE TITLE
Why is an emoji ☺ added during encoding and decoding?

### ISSUE THREAD

**Issue by gnohgnailoug** [meta-llama/codellama#87]
def encode_infilling(self, s: str) -> List[int]:
      """Encode a string without an implicit leading space."""
      return self.sp_model.encode("☺" + s)[2:]

  def decode_infilling(self, t: List[int]) -> str:
      """Decode a string without an implicit leading space."""
      return self.sp_model.decode([self.sp_model.piece_to_id("☺")] + t)[1:]

I don't understand why '☺' is added to the input during encoding? Could you help me? Thanks!

**Comment by faabian** [comment]
Thanks for the question. SentencePiece tokenizers add an implicit leading space when encoding a sentence (i.e. "Hello world" would be encoded as " Hello world" would be in the middle of a string). Because in our prompt format, the middle and suffix should not have an added implicit leading space, we need to suppress it when encoding with SentencePiece. This "hack" achieves that by simulating that the sentence is contained in a larger string. We could use any prefix to add under the condition that its last token does not merge to the right with any other token. In our vocabulary, the emoji achieves that. Obviously this does not extend to other tokenizers, and the clean solution would be to add a switch to SentencePiece whether to suppress the implicit leading space upon a single encoding (there is a global switch but not a per-prompt one).

See also the solution by HuggingFace which does not need this "hack": https://github.com/huggingface/transformers/blob/5af2c6269672cda01c24ad48fab13f14a3ffb746/src/transformers/models/code_llama/tokenization_code_llama.py#L255
